name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Log in GitGub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
